;;; grove-theme.el --- Grove theme for Doom Emacs -*- lexical-binding: t; no-byte-compile: t; -*-
;;; Commentary:
;;; Code:

(require 'doom-themes)

(defgroup grove-theme nil
  "Options for the `grove' theme."
  :group 'doom-themes)

(defcustom grove-padded-modeline doom-themes-padded-modeline
  "If non-nil, adds padding to the mode-line."
  :group 'grove-theme
  :type '(choice integer boolean))

(def-doom-theme grove
  "A dark green theme based on the Grove desktop palette."
  :family 'grove
  :background-mode 'dark

  ((bg         '("@theme-bg@" "black"       "black"))
   (bg-alt     '("@theme-bg-alt@" "black"       "black"))
   (base0      '("@theme-bg@" "black"       "black"))
   (base1      '("@theme-bg@" "black"       "black"))
   (base2      '("@theme-bg-alt@" "black"       "black"))
   (base3      '("@theme-bg-tertiary@" "brightblack" "brightblack"))
   (base4      '("@theme-border@" "brightblack" "brightblack"))
   (base5      '("@theme-muted@" "brightblack" "brightblack"))
   (base6      '("@theme-base@" "green"       "green"))
   (base7      '("@theme-fg-alt@" "white"       "white"))
   (base8      '("@theme-fg@" "white"       "brightwhite"))
   (fg         '("@theme-fg@" "white"       "brightwhite"))
   (fg-alt     '("@theme-fg-alt@" "white"       "white"))

   (grey       base5)
   (red        '("@theme-red@" "red"         "brightred"))
   (orange     '("@theme-orange@" "yellow"      "brightyellow"))
   (green      '("@theme-green@" "green"       "green"))
   (teal       '("@theme-teal@" "cyan"        "brightgreen"))
   (yellow     '("@theme-yellow@" "yellow"      "yellow"))
   (blue       '("@theme-blue@" "blue"        "brightblue"))
   (dark-blue  '("@theme-border@" "blue"        "blue"))
   (magenta    '("@theme-magenta@" "magenta"     "brightmagenta"))
   (violet     '("@theme-violet@" "magenta"     "magenta"))
   (cyan       '("@theme-cyan@" "cyan"        "brightcyan"))
   (dark-cyan  '("@theme-dark-cyan@" "cyan"        "cyan"))
   (bright-yellow '("@theme-bright-yellow@" "brightyellow" "yellow"))

   (highlight      green)
   (vertical-bar   base4)
   (selection      base4)
   (comments       '("@theme-syntax-comment@" "green"       "green"))
   (doc-comments   comments)
   (constants      '("@theme-syntax-constant@" "magenta"     "magenta"))
   (functions      '("@theme-syntax-function@" "magenta"     "brightmagenta"))
   (keywords       '("@theme-syntax-keyword@" "cyan"        "brightcyan"))
   (builtin        keywords)
   (methods        '("@theme-syntax-string@" "green"       "brightgreen"))
   (operators      '("@theme-syntax-operator@" "white"       "white"))
   (type           '("@theme-syntax-type@" "blue"        "brightblue"))
   (strings        '("@theme-syntax-string@" "green"       "brightgreen"))
   (variables      '("@theme-syntax-variable@" "white"       "brightwhite"))
   (numbers        '("@theme-syntax-number@" "yellow"      "brightyellow"))
   (region         base4)
   (error          '("@theme-syntax-exception@" "red"         "brightred"))
   (warning        yellow)
   (success        green)
   (markup-heading  '("@theme-markup-heading@" "green"       "green"))
   (markup-link     '("@theme-markup-link@" "cyan"        "brightcyan"))
   (markup-emphasis '("@theme-markup-emphasis@" "yellow"      "yellow"))
   (markup-strong   '("@theme-markup-strong@" "green"       "brightgreen"))
   (markup-code     '("@theme-markup-code@" "yellow"      "brightyellow"))
   (markup-quote    '("@theme-markup-quote@" "green"       "green"))
   (markup-muted    '("@theme-markup-muted@" "brightblack" "brightblack"))
   (diff-added-color    '("@theme-diff-added@" "green"       "green"))
   (diff-removed-color  '("@theme-diff-removed@" "red"         "brightred"))
   (diff-modified-color '("@theme-diff-modified@" "yellow"      "brightyellow"))
   (diff-line-number    '("@theme-diff-line-number@" "green"       "green"))
   (diff-line-number-active '("@theme-diff-line-number-active@" "white" "brightwhite"))
   (vc-modified    diff-modified-color)
   (vc-added       diff-added-color)
   (vc-deleted     diff-removed-color)

   (modeline-bg     bg-alt)
   (modeline-bg-alt bg)
   (modeline-fg     fg)
   (modeline-fg-alt base6)

   (-modeline-pad
    (when grove-padded-modeline
      (if (integerp grove-padded-modeline) grove-padded-modeline 4))))

  ((cursor :background dark-cyan)
   (hl-line :background bg-alt :extend t)
   ((line-number &override) :foreground diff-line-number)
   ((line-number-current-line &override) :foreground diff-line-number-active :background bg-alt)
   (fringe :background bg :foreground base4)
   (isearch :background green :foreground bg :weight 'bold)
   (lazy-highlight :background dark-cyan :foreground fg :weight 'bold)
   ((link &override) :foreground markup-link :underline t)
   (minibuffer-prompt :foreground green :weight 'bold)
   (show-paren-match :background base4 :foreground fg :weight 'bold)
   (vertical-border :background bg :foreground base4)

   (font-lock-property-name-face :foreground type)
   (font-lock-property-use-face :foreground type)
   (font-lock-escape-face :foreground fg-alt)
   (font-lock-regexp-face :foreground strings)
   (font-lock-operator-face :foreground operators)
   (font-lock-punctuation-face :foreground operators)
   (font-lock-bracket-face :foreground operators)
   (font-lock-delimiter-face :foreground operators)
   (font-lock-misc-punctuation-face :foreground operators)

   (mode-line
    :background modeline-bg :foreground modeline-fg
    :box (if -modeline-pad `(:line-width ,-modeline-pad :color ,modeline-bg)))
   (mode-line-inactive
    :background modeline-bg-alt :foreground modeline-fg-alt
    :box (if -modeline-pad `(:line-width ,-modeline-pad :color ,modeline-bg-alt)))
   (mode-line-emphasis :foreground green :weight 'bold)

   (doom-modeline-bar :background green)
   (doom-modeline-buffer-file :inherit 'mode-line-buffer-id :weight 'bold)
   (doom-modeline-buffer-path :foreground green :weight 'bold)
   (doom-modeline-buffer-project-root :foreground cyan :weight 'bold)
   (doom-modeline-buffer-modified :foreground yellow :weight 'bold)
   (doom-modeline-buffer-major-mode :foreground cyan :weight 'bold)
   (doom-modeline-info :foreground green :weight 'bold)
   (doom-modeline-warning :foreground warning :weight 'bold)
   (doom-modeline-error :foreground error :weight 'bold)

   (vertico-current :background base4 :foreground fg :extend t)
   (completions-common-part :foreground green :weight 'bold)
   (completions-first-difference :foreground cyan :weight 'bold)

   (ansi-color-black :foreground bg :background bg)
   (ansi-color-red :foreground red :background red)
   (ansi-color-green :foreground green :background green)
   (ansi-color-yellow :foreground yellow :background yellow)
   (ansi-color-blue :foreground blue :background blue)
   (ansi-color-magenta :foreground magenta :background magenta)
   (ansi-color-cyan :foreground cyan :background cyan)
   (ansi-color-white :foreground fg :background fg)
   (ansi-color-bright-black :foreground base5 :background base5)
   (ansi-color-bright-red :foreground violet :background violet)
   (ansi-color-bright-green :foreground strings :background strings)
   (ansi-color-bright-yellow :foreground bright-yellow :background bright-yellow)
   (ansi-color-bright-blue :foreground blue :background blue)
   (ansi-color-bright-magenta :foreground magenta :background magenta)
   (ansi-color-bright-cyan :foreground cyan :background cyan)
   (ansi-color-bright-white :foreground fg-alt :background fg-alt)
   (vterm-color-default :foreground fg :background bg)
   (vterm-color-black :foreground bg :background bg)
   (vterm-color-red :foreground red :background red)
   (vterm-color-green :foreground green :background green)
   (vterm-color-yellow :foreground yellow :background yellow)
   (vterm-color-blue :foreground blue :background blue)
   (vterm-color-magenta :foreground magenta :background magenta)
   (vterm-color-cyan :foreground cyan :background cyan)
   (vterm-color-white :foreground fg :background fg)

   (eshell-prompt :foreground green :weight 'bold)
   (eshell-ls-directory :foreground green :weight 'bold)
   (eshell-ls-executable :foreground cyan)
   (eshell-ls-symlink :foreground teal :weight 'bold)
   (eshell-ls-archive :foreground yellow)
   (eshell-ls-unreadable :foreground base5)

   (dired-directory :foreground green :weight 'bold)
   (dired-header :foreground cyan :weight 'bold)
   (dired-mark :foreground yellow :weight 'bold)
   (dired-marked :foreground yellow :weight 'bold)
   (dired-symlink :foreground teal :weight 'bold)

   (diff-added :foreground diff-added-color :background (doom-blend diff-added-color bg 0.12))
   (diff-changed :foreground diff-modified-color :background (doom-blend diff-modified-color bg 0.12))
   (diff-removed :foreground diff-removed-color :background (doom-blend diff-removed-color bg 0.12))
   (diff-refine-added :foreground diff-added-color :background (doom-blend diff-added-color bg 0.22))
   (diff-refine-changed :foreground diff-modified-color :background (doom-blend diff-modified-color bg 0.22))
   (diff-refine-removed :foreground diff-removed-color :background (doom-blend diff-removed-color bg 0.22))
   (diff-indicator-added :foreground diff-added-color)
   (diff-indicator-changed :foreground diff-modified-color)
   (diff-indicator-removed :foreground diff-removed-color)
   (diff-header :foreground diff-modified-color)
   (diff-file-header :foreground diff-added-color :weight 'bold)
   (diff-hunk-header :background base3 :foreground fg-alt)

   (markdown-header-face :inherit 'bold :foreground markup-heading)
   (markdown-header-delimiter-face :foreground markup-muted)
   (markdown-markup-face :foreground markup-muted)
   (markdown-bold-face :foreground markup-strong :weight 'bold)
   (markdown-italic-face :foreground markup-emphasis :slant 'italic)
   (markdown-code-face :background base3 :foreground markup-code)
   (markdown-pre-face :foreground markup-code)
   (markdown-blockquote-face :foreground markup-quote :slant 'italic)
   (markdown-link-face :foreground markup-link :underline t)
   (markdown-url-face :foreground markup-link)

   ((org-block &override) :background base3 :foreground fg-alt)
   ((org-block-background &override) :background base3)
   ((org-block-begin-line &override) :background base3 :foreground base5)
   ((org-block-end-line &override) :background base3 :foreground base5)
   ((org-code &override) :foreground markup-code)
   (org-date :foreground markup-link)
   (org-document-title :foreground markup-heading :weight 'bold)
   (org-document-info :foreground fg-alt)
   (org-drawer :foreground base6)
   (org-ellipsis :foreground markup-heading :underline nil)
   (org-formula :foreground cyan)
   (org-level-1 :foreground markup-heading :weight 'bold)
   (org-level-2 :foreground markup-link :weight 'bold)
   (org-level-3 :foreground markup-strong :weight 'bold)
   (org-level-4 :foreground markup-emphasis :weight 'bold)
   (org-link :foreground markup-link :underline t)
   (org-meta-line :foreground comments)
   (org-quote :background base3 :foreground markup-quote :slant 'italic)
   (org-table :foreground cyan)
   (org-tag :foreground base6 :weight 'normal)
   (org-todo :foreground green :weight 'bold)
   (org-done :foreground base6 :weight 'bold)
   (org-verbatim :foreground markup-code)

   (css-property :foreground type)
   (css-proprietary-property :foreground type)
   (css-selector :foreground functions)
   (web-mode-html-tag-face :foreground functions)
   (web-mode-html-tag-bracket-face :foreground operators)
   (web-mode-html-attr-name-face :foreground strings)
   (web-mode-html-attr-value-face :foreground strings)
   (web-mode-json-key-face :foreground functions)
   (web-mode-json-context-face :foreground operators)
   (js2-object-property :foreground type)
   (js2-function-param :foreground variables)

   (eglot-highlight-symbol-face :background base4)
   (flymake-error :underline `(:style wave :color ,red))
   (flymake-warning :underline `(:style wave :color ,yellow))
   (flymake-note :underline `(:style wave :color ,green))))

;;; grove-theme.el ends here
